### PR TITLE
KAN-21 refactor: change dir name

### PR DESCRIPTION
**Pull request by instaitincubator**

### CODE REVIEW

**Comment by instaitincubator** [comment]
run build production

**Review by gem4ik — APPROVED** [review]

**Comment by instaitincubator** [comment]
run build production

**Comment by instaitincubator** [comment]
run build production

**Review by gem4ik — APPROVED** [review]

**Comment by instaitincubator** [comment]
run build production

**Review by gem4ik — APPROVED** [review]

**Comment by instaitincubator** [comment]
run build production

**Review by gem4ik — APPROVED** [review]

**Comment by instaitincubator** [comment]
run build production

**Comment by instaitincubator** [comment]
run build production

**Pull request closed without merging**
