### PR TITLE
auth fixes 

### PR DESCRIPTION
**Pull request by gem4ik**
[fix local environment variable](https://github.com/instaitincubator/instagram/pull/81/commits/d534fd21152a98cdfb279286cddab5163570f09f)
--------------------------------------------
[fix email format error](https://github.com/instaitincubator/instagram/pull/81/commits/9dcc71cc5ff620e103bc39962776935015e426d1)
image
--------------------------------------------
[fix field required error](https://github.com/instaitincubator/instagram/pull/81/commits/3355927dcf0987228eb92c6b08be99410ff45cae)
image
--------------------------------------------
[fix server error handling in sign in form](https://github.com/instaitincubator/instagram/pull/81/commits/e82aa1f1e277702bb47a4750091a4ce0c1f3b449)
image
--------------------------------------------
[add checkbox error border](https://github.com/instaitincubator/instagram/pull/81/commits/c44419951ac8d7aeb07ba597aca2feb5d870e8b3)
image
--------------------------------------------
[try to add space in moda](https://github.com/instaitincubator/instagram/pull/81/commits/206d7178b51bee29a70d9dd608bb866ba79168c4)
тут надо перепроверить у меня из-за разрешения экрана любой длинный почта переносится на новую строку
--------------------------------------------
[Add refine method to validate spaces in passwords]
(https://github.com/instaitincubator/instagram/pull/81/commits/a3103ee84ea5c796041938d480067976fb2a93de)
добавил ошибка на пробелы в пароле
--------------------------------------------
[fix: reset sign up form on close modal](https://github.com/instaitincubator/instagram/pull/81/commits/c4ebe3160dda829461308cabd837c5740fb82960)
по нажатию на крестик в модалке теперь форма тоже сбрасывается
--------------------------------------------
[fix: render password recovery form issue](https://github.com/instaitincubator/instagram/pull/81/commits/f698d6475a3a749176b419db61de6625ffd18aec)
рендерится нужная страница

### CODE REVIEW

**Comment by gem4ik** [comment]
run build production

**Comment by gem4ik** [comment]
run build production

**Comment by gem4ik** [comment]
run build production

**Comment by gem4ik** [comment]
run build production

**Review by melion11 — APPROVED** [review]

**Pull request merged**
